export const RECEIVE_USERS = 'RECEIVE_USERS';
export const RECEIVE_TWEETS = 'RECEIVE_TWEETS';
export const AUTH_USER = 'AUTH_USER';
export const INCREMENT_LIKE = 'INCREMENT_LIKE';
export const DECREMENT_LIKE = 'DECREMENT_LIKE';
